import { chromium, devices } from 'playwright';
const b = await chromium.launch({executablePath: process.env.CHROMIUM || undefined});
const ctx = await b.newContext({...devices['iPhone 13'], isMobile:true, hasTouch:true});
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('dialog',d=>d.accept());
await p.goto('file:///home/claude/build/Testtrainer_standalone.html'); await p.waitForTimeout(500);
const vp = p.viewportSize(); console.log('Viewport:', vp.width+'×'+vp.height);
const ov = async ()=> await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
console.log('Dashboard Querlauf:', await ov(), 'px');
await p.screenshot({path:'m1-dash.png', fullPage:true});
console.log('Nav sichtbar:', await p.evaluate(()=>{const n=document.querySelector('nav');const r=n.getBoundingClientRect();return Math.round(r.width)+'px, rechts '+Math.round(r.right)+' von '+innerWidth;}));
await p.evaluate(()=>go('train')); await p.waitForTimeout(300);
console.log('Training Querlauf:', await ov(), 'px');
await p.screenshot({path:'m2-train.png', fullPage:true});
await p.evaluate(()=>start({view:'fr',typ:'frSim',zeit:1800,gesamt:true,titel:'Sprachtest'}));
await p.waitForTimeout(400);
console.log('Sprachtest Querlauf:', await ov(), 'px');
console.log('Exambar-Höhe:', await p.evaluate(()=>Math.round(document.querySelector('.exambar').getBoundingClientRect().height)));
console.log('Optionsbreite:', await p.evaluate(()=>Math.round(document.querySelector('.opt').getBoundingClientRect().width)));
await p.screenshot({path:'m3-fr.png', fullPage:true});
await p.evaluate(()=>{LAUF.ti=1;LAUF.i=2;renderFrage();}); await p.waitForTimeout(300);
await p.screenshot({path:'m4-wort.png'});
console.log(errs.length?'FEHLER '+errs.join('|'):'keine JS-Fehler');
await b.close();
